# Generated by Django 3.2.6 on 2021-10-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.EmailField(max_length=100)),
                ('telefon_nomer', models.CharField(max_length=9)),
                ('xabar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('narxi', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('rangi', models.CharField(max_length=100)),
                ('xotirasi', models.CharField(blank=True, max_length=100, null=True)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.kategoriya')),
            ],
            options={
                'verbose_name_plural': 'Tovarlar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Xaridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('familiya', models.CharField(max_length=200)),
                ('OtasiningIsmi', models.CharField(max_length=200)),
                ('manzil', models.CharField(max_length=250)),
                ('pasportSeriyaRaqami', models.CharField(max_length=9)),
                ('telefon', models.CharField(max_length=14)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='userImages')),
                ('qolganSumma', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('umumiyTolanganPul', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('muddat', models.IntegerField(choices=[(1, '1 oy'), (2, '2 oy'), (3, '3 oy'), (4, '4 oy'), (5, '5 oy'), (6, '6 oy'), (7, '7 oy'), (8, '8 oy'), (9, '9 oy'), (10, '10 oy'), (11, '11 oy'), (12, '12 oy')])),
                ('oylikTolovMiqdori', models.PositiveIntegerField(blank=True, null=True)),
                ('tanlanganTovar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.tovar')),
                ('tovarKategoriyasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.kategoriya')),
            ],
            options={
                'verbose_name_plural': 'Xaridorlar',
                'ordering': ['-ism'],
            },
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdori', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('vaqti', models.DateTimeField(auto_now_add=True)),
                ('xaridor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tolov', to='credit.xaridor')),
            ],
            options={
                'verbose_name_plural': "Barcha to'lovlar",
                'ordering': ['-vaqti'],
            },
        ),
    ]
