# Generated by Django 3.2.6 on 2021-10-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_auto_20211022_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users_message',
            options={'ordering': ['-Xabar_vaqti'], 'verbose_name_plural': 'Foydalanuvchilardan kelgan xabarlar'},
        ),
        migrations.RenameField(
            model_name='users_message',
            old_name='familiyasi',
            new_name='Familiya',
        ),
        migrations.RenameField(
            model_name='users_message',
            old_name='ismi',
            new_name='Ism',
        ),
        migrations.RenameField(
            model_name='users_message',
            old_name='telefon_raqami',
            new_name='Telefon_raqam',
        ),
        migrations.RenameField(
            model_name='users_message',
            old_name='xabar',
            new_name='Xabar',
        ),
        migrations.RenameField(
            model_name='users_message',
            old_name='xabar_yuborilgan_vaqt',
            new_name='Xabar_vaqti',
        ),
    ]
